server:
  port: 8080
spring:
  application:
    name: rocket-mq
#  datasource:
#    # 当前数据源操作类型
#    type: com.alibaba.druid.pool.DruidDataSource
#    # mysql驱动类
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/db2022?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
#    username: root
#    password: root
#
#  redis:
#    port: 6379
#    host: localhost
#    database: 0
#    connect-timeout: 30

#mybatis:
#  mapper-locations: classpath*:mapper/*.xml
#  type-aliases-package: com.szm.redis.performance.entities

rocketmq:
  name-server: http://192.168.88.130:9876 #rocketmq服务地址

  producer:
    group: rocketmq_test #自定义的组名称
    send-message-timeout: 3000 #消息发送超时时长